In [ ]:
import pandas as pd

In [7]:
file_path = "../csv/Error 1.csv"
data = pd.read_csv(file_path)
error_code_frequency_index = data[data.iloc[:, 0].str.contains("ERROR CODE FREQUENCY")].index[0]

df_ecl = data.iloc[0:error_code_frequency_index, ]
df_ecf = data.iloc[error_code_frequency_index: , ]

In [8]:
df_ecl.head(5)

  |------------------------------------------------- ERROR CODE LISTING -------------------------------------------------|
0                                            LEGEND:
1  Ticks (hex):       Internal time from power-on...
2                     Speed (km/h):      Train speed
3                    Speed1 (km/h):     Axle 1 speed
4                    Speed2 (km/h):     Axle 2 speed

In [9]:
df_ecl.tail(5)

    |------------------------------------------------- ERROR CODE LISTING -------------------------------------------------|
124  116;0x0037;0x000D9C72;6/8/24;17:36:35;0x000;12...
125  117;0x6047;0x000D9DF2;6/8/24;17:36:35;0x000;6;...
126  118;0x6017;0x000D9DF2;6/8/24;17:36:35;0x000;6;...
127  119;0x6027;0x000D9DF2;6/8/24;17:36:35;0x000;6;...
128  120;0x6037;0x000D9DF2;6/8/24;17:36:35;0x000;6;...

In [10]:
df_ecf.head(5)

    |------------------------------------------------- ERROR CODE LISTING -------------------------------------------------|
129  |---------------------------------------------...
130                   Code(hex);Frequency;Description;
131                         0x6017;11;AXLE1_LOCK  GONE
132                         0x6027;10;AXLE2_LOCK  GONE
133                         0x6037;11;AXLE3_LOCK  GONE

In [11]:
df_ecf.tail(5)

    |------------------------------------------------- ERROR CODE LISTING -------------------------------------------------|
149                                0x0025;1;E_DV2_TOUT
150                                0x0032;1;E_SENS_FR3
151                                0x0035;1;E_DV3_TOUT
152                                0x0042;1;E_SENS_FR4
153                                0x0045;2;E_DV4_TOUT

In [12]:
df_ecl_formatted = df_ecl.iloc[8:].reset_index(drop=True) # Skip some rows that are not required
df_ecl_formatted = df_ecl_formatted.iloc[:, 0].str.split(';', expand=True) # Split the text into separate with ';' as delimiter 
df_ecl_formatted.columns = df_ecl_formatted.iloc[0] # Reassign columns 
df_ecl_formatted = df_ecl_formatted.drop(df_ecl_formatted.columns[[0, -1]], axis=1) # Drop unrequired columns
df_ecl_formatted = df_ecl_formatted.iloc[1:].reset_index(drop=True) # Reset the index
df_ecl_formatted

,Code(hex),Ticks(hex),Date,Time,SW(hex),Speed(km/h),Speed1(km/h),Speed2(km/h),Speed3(km/h),Speed4(km/h),...,DEVICE_ON,V5,V45,ZERO_SPEED,WSP_FAILURE,V5_2,V30,V5_1,Condition,Description
0,0xA000,0x00000AAC,31/7/24,13:28:13,0x000,40,40,40,40,40,...,1,1,0,0,1,0,0,1,0,I_POWER_ON
1,0x0017,0x000057D7,31/7/24,13:28:53,0x000,34,0,0,0,0,...,1,1,0,0,1,0,0,1,0,AXLE1_LOCK
2,0x0037,0x000057E3,31/7/24,13:28:53,0x000,34,0,0,0,0,...,1,1,0,0,1,0,0,1,0,AXLE3_LOCK
3,0x0027,0x000057FB,31/7/24,13:28:53,0x000,34,0,0,0,0,...,1,1,0,0,0,0,0,1,0,AXLE2_LOCK
4,0x0047,0x000057FB,31/7/24,13:28:53,0x000,34,0,0,0,0,...,1,1,0,0,0,0,0,1,0,AXLE4_LOCK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,0x0037,0x000D9C72,6/8/24,17:36:35,0x000,12,0,0,0,0,...,1,1,0,0,0,0,1,1,0,AXLE3_LOCK
116,0x6047,0x000D9DF2,6/8/24,17:36:35,0x000,6,0,0,0,0,...,1,1,0,0,0,0,1,1,0,AXLE4_LOCK GONE
117,0x6017,0x000D9DF2,6/8/24,17:36:35,0x000,6,0,0,0,0,...,1,1,0,0,0,0,1,1,0,AXLE1_LOCK GONE
118,0x6027,0x000D9DF2,6/8/24,17:36:35,0x000,6,0,0,0,0,...,1,1,0,0,0,0,1,1,0,AXLE2_LOCK GONE
119,0x6037,0x000D9DF2,6/8/24,17:36:35,0x000,6,0,0,0,0,...,1,1,0,0,0,0,1,1,0,AXLE3_LOCK GONE

In [13]:
df_ecf_formatted = df_ecf.iloc[1:].reset_index(drop=True) # Skip some rows that are not required
df_ecf_formatted = df_ecf_formatted.iloc[:, 0].str.split(';', expand=True) # Split the text into separate with ';' as delimiter 
df_ecf_formatted.columns = df_ecf_formatted.iloc[0] # Reassign columns 
df_ecf_formatted = df_ecf_formatted.drop(df_ecf_formatted.columns[-1], axis=1) # Drop unrequired columns
df_ecf_formatted = df_ecf_formatted.iloc[1:].reset_index(drop=True) # Reset the index
df_ecf_formatted

0  Code(hex) Frequency       Description
0     0x6017        11  AXLE1_LOCK  GONE
1     0x6027        10  AXLE2_LOCK  GONE
2     0x6037        11  AXLE3_LOCK  GONE
3     0x6047        11  AXLE4_LOCK  GONE
4     0x6012         1   E_SENS_FR1 GONE
5     0x6015         2   E_DV1_TOUT GONE
6     0x6022         1   E_SENS_FR2 GONE
7     0x6025         1   E_DV2_TOUT GONE
8     0x6035         1   E_DV3_TOUT GONE
9     0x6045         2   E_DV4_TOUT GONE
10    0xA000        12        I_POWER_ON
11    0x0017        11        AXLE1_LOCK
12    0x0027        10        AXLE2_LOCK
13    0x0037        11        AXLE3_LOCK
14    0x0047        11        AXLE4_LOCK
15    0x0012         2        E_SENS_FR1
16    0x0015         2        E_DV1_TOUT
17    0x0022         4        E_SENS_FR2
18    0x0025         1        E_DV2_TOUT
19    0x0032         1        E_SENS_FR3
20    0x0035         1        E_DV3_TOUT
21    0x0042         1        E_SENS_FR4
22    0x0045         2        E_DV4_TOUT

In [14]:
summary = df_ecl_formatted.groupby(by=["Description", "Code(hex)"], as_index=False).size()
summary.head()

        Description Code(hex)  size
0        AXLE1_LOCK    0x0017    11
1  AXLE1_LOCK  GONE    0x6017    11
2        AXLE2_LOCK    0x0027    10
3  AXLE2_LOCK  GONE    0x6027    10
4        AXLE3_LOCK    0x0037    11